package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class AddRoomController {
	@FXML
	private TextField tbRoomTitle;
	@FXML
	private Button btnAddRoom;

	// Event Listener on Button[#btnAddRoom].onAction
	@FXML
	public void actionAddRoom(ActionEvent event) {
		// TODO Autogenerated
	}
}
