package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class HomeController {
	@FXML
	private Button btnGotoDashboard;
	@FXML
	private Button btnGotoUsers;
	@FXML
	private Button btnGotoNetworks;
	@FXML
	private Button btnGotoPayment;
	@FXML
	private Button btnGotoPaymentHistory;
	@FXML
	private Button btnGetCustomerSupport;
	@FXML
	private Button btnExit;

	// Event Listener on Button[#btnGotoDashboard].onAction
	@FXML
	public void actionGotoDashboard(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("res/DashboardScene.fxml"));
			Parent root = loader.load();
			Stage stage = new Stage();
			stage.setScene(new Scene(root));

			// Show the new stage (window)
			stage.show();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnGotoUsers].onAction
	@FXML
	public void actionGotoUsers(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnGotoNetworks].onAction
	@FXML
	public void actionGotoNetworks(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnGotoPayment].onAction
	@FXML
	public void actionGotoPayment(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnGotoPaymentHistory].onAction
	@FXML
	public void actionGotoPaymentHistory(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnGetCustomerSupport].onAction
	@FXML
	public void actionGetCustomerSupport(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void actionExitApp(ActionEvent event) {
		// TODO Autogenerated
	}
}
