package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class LoginController {
	@FXML
	private TextField tfCnic;
	@FXML
	private Button btnLogin;
	@FXML
	private TextField tfPassword;

	// Event Listener on TextField[#tfCnic].onAction
	@FXML
	public void actionGetCnic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void actionLogin(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfPassword].onAction
	@FXML
	public void actionGetPassword(ActionEvent event) {
		// TODO Autogenerated
	}
}
